name: CI/CD Pipeline

on:
  push:
    branches: [ feature/ci-cd ]
  pull_request:
    branches: [ feature/ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes (com banco mockado)
        env:
          USE_MOCK_DB: "true" # 💡 sinaliza pro app usar mongomock
          SECRET_KEY: ${{ secrets.SECRET_KEY }} # Teste
          ALGORITHM: "HS256"
          ACCESS_TOKEN_EXPIRE_MINUTES: "60"
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest -v tests/
