name: CI/CD Pipeline

on:
  push:
    branches: [ feature/ci-cd ]
  pull_request:
    branches: [ feature/ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install pytest pytest-asyncio mongomock


      - name: Rodar testes
        run: |
              export PYTHONPATH=$PYTHONPATH:$(pwd)/src
              export MONGO_URI="mongomock://localhost"  # Dummy Mongo para testes CI
              export SECRET_KEY="dummysecret"
              export ALGORITHM="HS256"
              export ACCESS_TOKEN_EXPIRE_MINUTES="60"
              
              pytest -v tests/
