name: CI/CD Pipeline

on:
  push:
    branches: [ feature/ci-cd ]
  pull_request:
    branches: [ feature/ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Rodar testes
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          export MONGO_URI=${{ secrets.MONGO_URI }}
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          export ALGORITHM=${{ secrets.ALGORITHM }}
          export ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          pytest -v tests/
