name: CI/CD Pipeline

on:
  push:
    branches: [ feature/ci-cd ]  # Pode trocar pra main depois
  pull_request:
    branches: [ feature/ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes (com banco mockado)
        env:
          USE_MOCK_DB: "true"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: "HS256"
          ACCESS_TOKEN_EXPIRE_MINUTES: "60"
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest -v tests/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/ci-cd'  # Só roda o deploy nessa branch
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/meuapp:latest .

      - name: Push da imagem para Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/meuapp:latest
