name: CI/CD Pipeline

# Executa em pushes ou PRs na branch de feature
on:
  push:
    branches: [ feature/ci-cd ]
  pull_request:
    branches: [ feature/ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Puxar código do repo
    - name: Checar código
      uses: actions/checkout@v3

    # 2️⃣ Configurar Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3️⃣ Instalar dependências
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio mongomock

    # 4️⃣ Rodar testes
    - name: Rodar testes
      run: pytest -v tests/

    # 5️⃣ Build da imagem Docker
    - name: Build Docker
      run: docker build -t teste-api .
